import telebot

APP_VERSION = '23092023'

IS_TEST = False
TELEGRAM_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' if IS_TEST else 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY'
bot = telebot.TeleBot(TELEGRAM_TOKEN)

INFORMER_CHAT_ID = '-ZZZZZZZZZZZ'
ON_INFORMER = not IS_TEST